kumuluzee:
  name: recommendation-system
  version: 1.0.0
  env:
    name: dev
  server:
    base-url: http://localhost:3334/v1/recommendation
    #base-url: http://prpo-priporocilni-sistem-prpo-priporocilni-sistem.apps.us-west-1.starter.openshift-online.com/v1/priporocila
    http:
      port: 3333
  datasources:
    - jndi-name: jdbc/ItemDS
      connection-url: jdbc:postgresql://fanny.db.elephantsql.com:5432/sewztpca
      username: sewztpca
      password: jviqrny5vLJYogFEeyBhAr7daifOAiwB
      max-pool-size: 20
rest-properties:
  test-config: test01
