kumuluzee:
  name: recommendation-system
  version: 1.0.0
  env:
    name: dev
  server:
    http:
      port: 3333
  datasources:
    - jndi-name: jdbc/ItemDS
      #connection-url: jdbc:postgresql://localhost:5432/rentarich
      #connection-url: jdbc:postgresql://database:5432/rentarich
      connection-url: jdbc:postgresql://fanny.db.elephantsql.com:5432/sewztpca
      username: sewztpca
      password: jviqrny5vLJYogFEeyBhAr7daifOAiwB
      #username: postgres
      #password: postgres
      max-pool-size: 1
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/ItemDS
  metrics:
    servlet:
      enabled: true
      mapping: /metrics
  openapi:
    ui:
      enabled: true
  config:
    consul:
      agent: http://20.62.179.11/consul
    #start-retry-delay-ms: 200
    #max-retry-delay-ms: 900000
    #etcd:
      #hosts: http://20.120.64.140:2379
  cors-filter:
    servlet:
      allow-generic-http-requests: true
      allow-origin: "*"
    annotations:
      my-resource:
        allow-origin: "http://localhost:4200"
        allow-subdomains: true
        supported-methods: "GET, POST, DELETE, HEAD, OPTIONS, PUT"
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                            <Configuration name="comments">
                                <Appenders>
                                    <Console name="console" target="SYSTEM_OUT">
                                        <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                    </Console>
                                    <Socket name="logstash" host="bf305549-fb2a-4cc6-ac77-2a27465ac070-ls.logit.io"
                                    port="22895" protocol="udp">
                                        <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                    </Socket>
                                </Appenders>
                                <Loggers>
                                    <!-- Default logger -->
                                    <Root level="all">
                                        <AppenderRef ref="console" level="info" />
                                        <AppenderRef ref="logstash" level="info" />
                                    </Root>
                                </Loggers>
                            </Configuration>'

rest-properties:
  maintenance-mode: false
  broken: false
