kumuluzee:
  name: recommendation-system
  version: 1.0.0
  env:
    name: dev
  server:
    http:
      port: 3333
  datasources:
    - jndi-name: jdbc/ItemDS
      connection-url: jdbc:postgresql://localhost:5432/rentarich
      #connection-url: jdbc:postgresql://database:5432/rentarich
      #connection-url: jdbc:postgresql://fanny.db.elephantsql.com:5432/sewztpca
      #username: sewztpca
      #password: jviqrny5vLJYogFEeyBhAr7daifOAiwB
      username: postgres
      password: postgres
      max-pool-size: 20
rest-properties:
  test-config: test01
