kumuluzee:
  name: recommendation-system
  version: 1.0.0
  env:
    name: dev
  server:
    http:
      port: 3333
  datasources:
    - jndi-name: jdbc/ItemDS
      #connection-url: jdbc:postgresql://localhost:5432/rentarich
      #connection-url: jdbc:postgresql://database:5432/rentarich
      connection-url: jdbc:postgresql://fanny.db.elephantsql.com:5432/sewztpca
      username: sewztpca
      password: jviqrny5vLJYogFEeyBhAr7daifOAiwB
      #username: postgres
      #password: postgres
      max-pool-size: 1
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/ItemDS
  metrics:
    servlet:
      enabled: true
      mapping: /metrics
  openapi-mp:
    enabled: true
    ui:
      enabled: true
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                    <Configuration name="recommendation-system">
                        <Appenders>
                            <Console name="console" target="SYSTEM_OUT">
                                <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                            </Console>
                        </Appenders>
                        <Loggers>
                            <!-- Default logger -->
                            <Root level="info">
                                <AppenderRef ref="console"/>
                            </Root>
                        </Loggers>
                    </Configuration>'


rest-properties:
  maintenance-mode: false
  broken: false
