name: Build and push to Docker

on:
  push:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build & Test & Package with Maven
        run: |
          mvn mvn --show-version --update-snapshots --batch-mode clean package
      - name: Build a Docker image
        run: |
          mkdir target/dependency
          (cd target/dependency; jar -xf ../*.jar)
          docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/rso-recommendation:$(git rev-parse --short "$GITHUB_SHA")
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/rso-recommendation:$(git rev-parse --short "$GITHUB_SHA")
